services:
  - type: web
    name: new-macro-dashboard-v2
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: EODHD_API_TOKEN
        sync: false
